name: Install Linux dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          dav1d \
          glslang-tools \
          libvulkan-dev \
          libwayland-dev \
          libx11-dev \
          libx11-xcb-dev \
          libxcb1-dev \
          libxkbcommon-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxkbcommon-x11-dev \
          nasm \
          pkg-config \
          rav1e \
          wayland-protocols
    - shell: bash
      run: |
        set -euxo pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

