name: Install Linux dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euxo pipefail
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang \
          glslang-tools \
          libaom-dev \
          libclang-dev \
          libdav1d-dev \
          libde265-dev \
          libjpeg-dev \
          libheif-dev \
          libopenexr-dev \
          libpng-dev \
          librav1e-dev \
          libtiff-dev \
          libvulkan-dev \
          libwayland-dev \
          libx11-dev \
          libx11-xcb-dev \
          libx265-dev \
          libxcb1-dev \
          libxi-dev \
          libxkbcommon-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxkbcommon-x11-dev \
          libxrandr-dev \
          libwebp-dev \
          nasm \
          pkg-config \
          rav1e \
          wayland-protocols
    - shell: bash
      run: |
        set -euxo pipefail
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

