services:
  builder:
    build: .
    working_dir: /work
    stdin_open: true
    tty: true
    userns_mode: keep-id

    volumes:
      - .:/work:Z
      - ${HOME}/.cargo/registry/:/.cargo/registry:Z
      - ${HOME}/.cargo/git/:/.cargo/git:Z
      - cargo-bin:/.cargo/bin
      - rustup:/.rustup

    environment:
      - CARGO_HOME=/.cargo
      - RUSTUP_HOME=/.rustup

volumes:
  cargo-bin:
  rustup:
