name: Install Windows dependencies

runs:
  using: composite
  steps:
    - shell: pwsh
      run: |
        choco install -y vulkan-sdk

    - shell: pwsh
      run: |
        Invoke-WebRequest https://win.rustup.rs -OutFile rustup-init.exe
        .\rustup-init.exe -y

        "$env:USERPROFILE\.cargo\bin" | Out-File `
          -FilePath $env:GITHUB_PATH `
          -Encoding utf8 `
          -Append
