name: Build and test emimg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v7
        - uses: ./.github/actions/setup-linux
        - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - uses: davidlattimore/wild-action@latest
      - uses: ./.github/actions/setup-linux
      - run: cargo clippy --all-targets

  linux-no-libc:
    name: Linux (no libc)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - uses: davidlattimore/wild-action@latest
      - uses: ./.github/actions/setup-linux
      - run: cargo test

  linux-libc:
    name: Linux (libc)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - uses: davidlattimore/wild-action@latest
      - uses: ./.github/actions/setup-linux
      - run: cargo test --no-default-features --features=default-rust-libc

  macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/setup-macos
      - run: cargo test --all-features

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/setup-windows
      - run: cargo test --all-features

  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            set -eux

            pkg update
            pkg install -y \
              pkg-config \
              glslang \
              libxkbcommon \
              seatd \
              vulkan-loader \
              vulkan-headers \
              wayland \
              xorg

            fetch -o - https://sh.rustup.rs | sh -s -- -y
          run: |
            export PATH="$HOME/.cargo/bin:$PATH"
            cargo test --all-features
